package generator

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
	"yaml-anchor/pkg/scanner"
	"yaml-anchor/pkg/schema"
)

// ExportYAML takes a pipeline and writes it as YAML to the specified outputPath.
func ExportYAML(pipeline *schema.Pipeline, outputPath string) error {
	// Security: Scan for hardcoded secrets
	if err := scanner.HasSecret(pipeline); err != nil {
		return fmt.Errorf("yaml generation blocked: %w", err)
	}

	// Ensure the directory exists
	dir := filepath.Dir(outputPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory for YAML output: %w", err)
	}

	// Serialize the pipeline struct to YAML
	data, err := yaml.Marshal(pipeline)
	if err != nil {
		return fmt.Errorf("failed to marshal pipeline to YAML: %w", err)
	}

	// Add a comment to indicate it was auto-generated
	header := []byte("# Generated by YamlAnchor. DO NOT EDIT.\n")
	outputData := append(header, data...)

	// Write the YAML file
	if err := os.WriteFile(outputPath, outputData, 0644); err != nil {
		return fmt.Errorf("failed to write YAML file: %w", err)
	}

	return nil
}
