package generator_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"yaml-anchor/pkg/generator"
	"yaml-anchor/pkg/schema"
)

func samplePipeline() *schema.Pipeline {
	return &schema.Pipeline{
		Name: "Test Pipeline",
		On:   &schema.Triggers{Push: &schema.PushTrigger{Branches: []string{"main"}}},
		Jobs: map[string]schema.Job{
			"test": {
				RunsOn: "ubuntu-latest",
				Steps: []schema.Step{
					{Name: "Checkout", Uses: "actions/checkout@v4"},
					{Name: "Run Tests", Run: "go test ./..."},
				},
			},
		},
	}
}

func TestExportYAML_CreatesFile(t *testing.T) {
	dir := t.TempDir()
	outPath := filepath.Join(dir, ".github", "workflows", "main.yml")

	if err := generator.ExportYAML(samplePipeline(), outPath); err != nil {
		t.Fatalf("ExportYAML returned error: %v", err)
	}

	if _, err := os.Stat(outPath); os.IsNotExist(err) {
		t.Fatalf("expected output file %q to exist, but it does not", outPath)
	}
}

func TestExportYAML_ContainsExpectedFields(t *testing.T) {
	dir := t.TempDir()
	outPath := filepath.Join(dir, "main.yml")

	if err := generator.ExportYAML(samplePipeline(), outPath); err != nil {
		t.Fatalf("ExportYAML returned error: %v", err)
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("could not read output file: %v", err)
	}
	content := string(data)

	checks := []string{
		"Test Pipeline",
		"ubuntu-latest",
		"go test ./...",
		"Generated by YamlAnchor",
	}
	for _, want := range checks {
		if !strings.Contains(content, want) {
			t.Errorf("expected output to contain %q, but it did not\nFull output:\n%s", want, content)
		}
	}
}

func TestExportYAML_BlockedBySecret(t *testing.T) {
	p := samplePipeline()
	p.Jobs["test"] = schema.Job{
		RunsOn: "ubuntu-latest",
		Steps: []schema.Step{
			{Name: "Upload", Run: "aws s3 cp . s3://bucket --key AKIAIOSFODNN7EXAMPLE"},
		},
	}

	dir := t.TempDir()
	outPath := filepath.Join(dir, "main.yml")

	err := generator.ExportYAML(p, outPath)
	if err == nil {
		t.Fatal("expected ExportYAML to return an error due to hardcoded secret, got nil")
	}
	if !strings.Contains(err.Error(), "blocked") {
		t.Errorf("expected error message to mention 'blocked', got: %v", err)
	}
}

func TestExportYAML_CreatesParentDirs(t *testing.T) {
	dir := t.TempDir()
	// Deep nested path that does not exist yet
	outPath := filepath.Join(dir, "a", "b", "c", "workflow.yml")

	if err := generator.ExportYAML(samplePipeline(), outPath); err != nil {
		t.Fatalf("ExportYAML should create parent dirs, got error: %v", err)
	}

	if _, err := os.Stat(outPath); os.IsNotExist(err) {
		t.Fatalf("expected file %q to be created", outPath)
	}
}

func TestExportYAML_StepEnvPresent(t *testing.T) {
	p := &schema.Pipeline{
		Name: "Env Test",
		On:   &schema.Triggers{Push: &schema.PushTrigger{Branches: []string{"main"}}},
		Jobs: map[string]schema.Job{
			"build": {
				RunsOn: "ubuntu-latest",
				Steps: []schema.Step{
					{
						Name: "Build",
						Run:  "go build ./...",
						Env:  map[string]string{"CGO_ENABLED": "0", "GOOS": "linux"},
					},
				},
			},
		},
	}

	dir := t.TempDir()
	outPath := filepath.Join(dir, "main.yml")
	if err := generator.ExportYAML(p, outPath); err != nil {
		t.Fatalf("ExportYAML returned error: %v", err)
	}

	data, _ := os.ReadFile(outPath)
	content := string(data)
	if !strings.Contains(content, "CGO_ENABLED") {
		t.Error("expected step env var CGO_ENABLED to appear in YAML output")
	}
}
