// Package gitlab implements a GitLab CI YAML exporter for YamlAnchor pipelines.
//
// Mapping reference:
//   - anchor jobs       → GitLab jobs (top-level keys)
//   - runs-on           → tags: (self-hosted) or image: (ubuntu/node/etc.)
//   - steps[].run       → script: lines
//   - steps[].uses      → script: comment + best-effort equivalent
//   - needs             → needs: (GitLab DAG mode)
//   - env               → variables:
//   - strategy.matrix   → parallel: matrix:
//   - if                → rules: → if:
//   - timeout-minutes   → timeout: N minutes
//   - services          → services:
package gitlab

import (
	"fmt"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
	"yaml-anchor/pkg/schema"
)

// Exporter renders YamlAnchor pipelines as .gitlab-ci.yml content.
type Exporter struct{}

// New returns a new GitLab CI Exporter.
func New() *Exporter { return &Exporter{} }

// Name returns the platform identifier.
func (e *Exporter) Name() string { return "gitlab" }

// DefaultOutputPath returns the conventional GitLab CI file path.
func (e *Exporter) DefaultOutputPath() string { return ".gitlab-ci.yml" }

// Export renders a YamlAnchor pipeline as GitLab CI YAML.
func (e *Exporter) Export(pipeline *schema.Pipeline) ([]byte, error) {
	doc := make(map[string]interface{})

	// Collect all stages in dependency order for the global stages: block
	stages := collectStages(pipeline)
	if len(stages) > 0 {
		doc["stages"] = stages
	}

	// Global variables from pipeline-level env
	if len(pipeline.Env) > 0 {
		doc["variables"] = pipeline.Env
	}

	// Workflow name (GitLab 15.3+)
	if pipeline.Name != "" {
		doc["workflow"] = map[string]interface{}{
			"name": pipeline.Name,
		}
	}

	// Render each job
	sortedIDs := sortedJobIDs(pipeline.Jobs)
	for _, jobID := range sortedIDs {
		job := pipeline.Jobs[jobID]
		gitlabJob, err := renderJob(jobID, job, stages)
		if err != nil {
			return nil, fmt.Errorf("job %q: %w", jobID, err)
		}
		doc[jobID] = gitlabJob
	}

	out, err := yaml.Marshal(doc)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal GitLab CI YAML: %w", err)
	}

	header := "# Generated by YamlAnchor — https://github.com/AyushCN/fusiontech\n" +
		"# Platform: GitLab CI\n\n"

	return append([]byte(header), out...), nil
}

// renderJob converts a single YamlAnchor job to a GitLab CI job map.
func renderJob(jobID string, job *schema.Job, allStages []string) (map[string]interface{}, error) {
	gj := make(map[string]interface{})

	// stage — position in the dependency graph
	stage := stageForJob(jobID, allStages)
	if stage != "" {
		gj["stage"] = stage
	}

	// image — from runs-on label
	image := resolveImage(job)
	if image != "" {
		gj["image"] = image
	}

	// tags — if runs-on has self-hosted labels, use tags
	labels := job.RunsOnLabels()
	if isLabelBased(labels) {
		gj["tags"] = labels
	}

	// needs — GitLab DAG-style dependencies
	if len(job.Needs) > 0 {
		needs := make([]map[string]interface{}, 0, len(job.Needs))
		for _, n := range job.Needs {
			needs = append(needs, map[string]interface{}{"job": n})
		}
		gj["needs"] = needs
	}

	// variables — job-level env vars
	if len(job.Env) > 0 {
		gj["variables"] = job.Env
	}

	// rules — from if: condition
	if job.If != "" {
		gj["rules"] = []map[string]interface{}{
			{"if": convertIfExpression(job.If)},
		}
	}

	// timeout
	if job.TimeoutMinutes > 0 {
		gj["timeout"] = fmt.Sprintf("%d minutes", job.TimeoutMinutes)
	}

	// services
	if len(job.Services) > 0 {
		services := make([]map[string]interface{}, 0, len(job.Services))
		for _, svc := range job.Services {
			s := map[string]interface{}{"name": svc.Image}
			services = append(services, s)
		}
		gj["services"] = services
	}

	// script — from steps
	script, beforeScript := renderSteps(job.Steps)
	if len(beforeScript) > 0 {
		gj["before_script"] = beforeScript
	}
	if len(script) > 0 {
		gj["script"] = script
	} else {
		// GitLab requires at least one script line
		gj["script"] = []string{"echo 'no run steps'"}
	}

	// parallel matrix — strategy.matrix
	if job.Strategy != nil && job.Strategy.Matrix != nil {
		parallel := renderMatrix(job.Strategy.Matrix)
		if parallel != nil {
			gj["parallel"] = parallel
		}
	}

	return gj, nil
}

// renderSteps converts YamlAnchor steps to before_script + script lines.
// setup-type uses: (checkout, setup-go, setup-node) go to before_script.
func renderSteps(steps []*schema.Step) (script []string, beforeScript []string) {
	for _, step := range steps {
		switch step.Type() {
		case schema.StepTypeRun:
			label := ""
			if step.Name != "" {
				label = fmt.Sprintf("# %s", step.Name)
			}
			lines := strings.Split(strings.TrimSpace(step.Run), "\n")
			if label != "" {
				script = append(script, label)
			}
			script = append(script, lines...)

		case schema.StepTypeUsesActionRemote, schema.StepTypeUsesActionLocal:
			// Map well-known actions to GitLab equivalents; others emit a comment
			comment := shimAction(step)
			if isSetupAction(step.Uses) {
				beforeScript = append(beforeScript, comment...)
			} else {
				script = append(script, comment...)
			}

		case schema.StepTypeUsesDockerURL:
			script = append(script, fmt.Sprintf("# docker step: %s", step.Uses))

		case schema.StepTypeReusableWorkflowLocal, schema.StepTypeReusableWorkflowRemote:
			script = append(script, fmt.Sprintf("# reusable workflow: %s (trigger manually or via GitLab child pipelines)", step.Uses))
		}
	}
	return script, beforeScript
}

// shimAction maps known GitHub Actions to GitLab-equivalent shell commands.
func shimAction(step *schema.Step) []string {
	uses := step.Uses
	switch {
	case strings.HasPrefix(uses, "actions/checkout"):
		return []string{"# actions/checkout — GitLab auto-clones; git fetch if needed",
			"git fetch --depth=1 || true"}
	case strings.HasPrefix(uses, "actions/setup-go"):
		goVersion := ""
		if v, ok := step.With["go-version"]; ok {
			goVersion = fmt.Sprintf("%v", v)
		}
		if goVersion != "" {
			return []string{fmt.Sprintf("# actions/setup-go@v4 — using Go %s", goVersion),
				fmt.Sprintf("echo 'Go %s assumed available via image'", goVersion)}
		}
		return []string{"# actions/setup-go — ensure Go is available in image"}
	case strings.HasPrefix(uses, "actions/setup-node"):
		nodeVersion := ""
		if v, ok := step.With["node-version"]; ok {
			nodeVersion = fmt.Sprintf("%v", v)
		}
		if nodeVersion != "" {
			return []string{fmt.Sprintf("# actions/setup-node — Node %s", nodeVersion),
				fmt.Sprintf("echo 'Node %s assumed available via image'", nodeVersion)}
		}
		return []string{"# actions/setup-node — ensure Node is available in image"}
	case strings.HasPrefix(uses, "actions/upload-artifact"):
		return []string{"# actions/upload-artifact — use GitLab artifacts: instead",
			"# See: https://docs.gitlab.com/ee/ci/yaml/#artifacts"}
	case strings.HasPrefix(uses, "actions/download-artifact"):
		return []string{"# actions/download-artifact — use GitLab needs: artifacts: instead"}
	case strings.HasPrefix(uses, "actions/cache"):
		return []string{"# actions/cache — use GitLab cache: block instead",
			"# See: https://docs.gitlab.com/ee/ci/yaml/#cache"}
	case strings.HasPrefix(uses, "docker/"):
		return []string{fmt.Sprintf("# docker action: %s — configure Docker-in-Docker in GitLab", uses)}
	default:
		comment := fmt.Sprintf("# uses: %s — no direct GitLab equivalent; implement manually", uses)
		if step.Name != "" {
			comment = fmt.Sprintf("# %s (%s) — no direct GitLab equivalent", step.Name, uses)
		}
		return []string{comment}
	}
}

func isSetupAction(uses string) bool {
	setupPrefixes := []string{
		"actions/checkout",
		"actions/setup-go",
		"actions/setup-node",
		"actions/setup-python",
		"actions/setup-java",
	}
	for _, p := range setupPrefixes {
		if strings.HasPrefix(uses, p) {
			return true
		}
	}
	return false
}

// resolveImage maps runner labels to GitLab image names.
func resolveImage(job *schema.Job) string {
	labels := job.RunsOnLabels()
	if len(labels) == 0 {
		return "ubuntu:22.04"
	}
	runner := labels[0]
	switch runner {
	case "ubuntu-latest", "ubuntu-22.04":
		return "ubuntu:22.04"
	case "ubuntu-20.04":
		return "ubuntu:20.04"
	case "macos-latest", "macos-13", "macos-12":
		// GitLab SaaS has macOS runners, but image: doesn't apply
		return ""
	case "windows-latest", "windows-2022", "windows-2019":
		// GitLab SaaS has Windows runners too
		return ""
	case "self-hosted":
		return "" // self-hosted uses tags, not image
	}
	// Unknown runner — use ubuntu as default
	return "ubuntu:22.04"
}

// isLabelBased returns true if the labels include self-hosted.
func isLabelBased(labels []string) bool {
	for _, l := range labels {
		if l == "self-hosted" {
			return true
		}
	}
	return false
}

// renderMatrix converts a YamlAnchor matrix to GitLab's parallel.matrix format.
func renderMatrix(raw interface{}) interface{} {
	m, ok := raw.(map[string]interface{})
	if !ok {
		return nil
	}

	var matrixEntries []map[string]interface{}
	var dimKeys []string
	for k := range m {
		if k == "include" || k == "exclude" {
			continue
		}
		dimKeys = append(dimKeys, k)
	}
	sort.Strings(dimKeys)

	if len(dimKeys) == 0 {
		return nil
	}

	entry := make(map[string]interface{})
	for _, k := range dimKeys {
		vals := m[k]
		if arr, ok := vals.([]interface{}); ok {
			var strVals []string
			for _, v := range arr {
				strVals = append(strVals, fmt.Sprintf("%v", v))
			}
			entry[k] = strVals
		}
	}
	matrixEntries = append(matrixEntries, entry)

	return map[string]interface{}{"matrix": matrixEntries}
}

// convertIfExpression does a best-effort conversion of GitHub Actions ${{ }}
// expressions to GitLab CI rule expressions.
func convertIfExpression(expr string) string {
	expr = strings.ReplaceAll(expr, "github.ref == 'refs/heads/main'", "$CI_COMMIT_BRANCH == \"main\"")
	expr = strings.ReplaceAll(expr, "github.ref == 'refs/heads/master'", "$CI_COMMIT_BRANCH == \"master\"")
	expr = strings.ReplaceAll(expr, "github.event_name == 'push'", "$CI_PIPELINE_SOURCE == \"push\"")
	expr = strings.ReplaceAll(expr, "github.event_name == 'pull_request'", "$CI_PIPELINE_SOURCE == \"merge_request_event\"")
	expr = strings.ReplaceAll(expr, "${{ ", "")
	expr = strings.ReplaceAll(expr, " }}", "")
	return expr
}

// collectStages returns an ordered list of stage names based on the job dependency graph.
// Used for the global `stages:` block in GitLab CI.
func collectStages(pipeline *schema.Pipeline) []string {
	visited := make(map[string]bool)
	stageOf := make(map[string]int)
	maxStage := 0

	var assign func(id string) int
	assign = func(id string) int {
		if s, ok := stageOf[id]; ok {
			return s
		}
		if visited[id] {
			return 0 // cycle guard
		}
		visited[id] = true
		job := pipeline.Jobs[id]
		if job == nil {
			return 0
		}
		maxDep := -1
		for _, need := range job.Needs {
			if s := assign(need); s > maxDep {
				maxDep = s
			}
		}
		s := maxDep + 1
		stageOf[id] = s
		if s > maxStage {
			maxStage = s
		}
		return s
	}

	ids := sortedJobIDs(pipeline.Jobs)
	for _, id := range ids {
		assign(id)
	}

	// Build named stages: stage-0, stage-1, ...
	// Use human-readable names based on the jobs at each level
	stageBuckets := make(map[int][]string)
	for id, s := range stageOf {
		stageBuckets[s] = append(stageBuckets[s], id)
	}

	stages := make([]string, 0, maxStage+1)
	for i := 0; i <= maxStage; i++ {
		// Use the first job name in this stage as the stage name (sorted)
		jobs := stageBuckets[i]
		sort.Strings(jobs)
		if len(jobs) == 1 {
			stages = append(stages, jobs[0])
		} else {
			stages = append(stages, fmt.Sprintf("stage-%d", i))
		}
	}

	return stages
}

// stageForJob returns the stage name for a given job ID.
func stageForJob(jobID string, allStages []string) string {
	// If the job name is directly a stage name, use it
	for _, s := range allStages {
		if s == jobID {
			return s
		}
	}
	// Otherwise fall back to the last stage (multi-job stages)
	if len(allStages) > 0 {
		return allStages[len(allStages)-1]
	}
	return ""
}

func sortedJobIDs(jobs map[string]*schema.Job) []string {
	ids := make([]string, 0, len(jobs))
	for id := range jobs {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	return ids
}
