package gitlab_test

import (
	"strings"
	"testing"

	"yaml-anchor/pkg/exporter/gitlab"
	"yaml-anchor/pkg/schema"
)

func pipeline(jobs map[string]*schema.Job) *schema.Pipeline {
	return &schema.Pipeline{Name: "Test Pipeline", Jobs: jobs}
}

func job(runsOn string, steps ...*schema.Step) *schema.Job {
	return &schema.Job{RunsOn: runsOn, Steps: steps}
}

func runStep(name, run string) *schema.Step {
	return &schema.Step{Name: name, Run: run}
}

func usesStep(uses string) *schema.Step {
	return &schema.Step{Uses: uses}
}

// --- Basic export ---

func TestExport_SingleJob_HasScriptAndImage(t *testing.T) {
	e := gitlab.New()
	p := pipeline(map[string]*schema.Job{
		"build": job("ubuntu-latest", runStep("Build", "go build ./...")),
	})
	out, err := e.Export(p)
	if err != nil {
		t.Fatalf("Export() error: %v", err)
	}
	s := string(out)
	if !strings.Contains(s, "image: ubuntu:22.04") {
		t.Errorf("expected 'image: ubuntu:22.04' in output, got:\n%s", s)
	}
	if !strings.Contains(s, "go build ./...") {
		t.Errorf("expected 'go build ./...' in script, got:\n%s", s)
	}
}

func TestExport_Header_ContainsGeneratedBy(t *testing.T) {
	e := gitlab.New()
	out, _ := e.Export(pipeline(map[string]*schema.Job{
		"build": job("ubuntu-latest", runStep("", "echo hi")),
	}))
	if !strings.Contains(string(out), "Generated by YamlAnchor") {
		t.Error("expected Generated by YamlAnchor header")
	}
}

func TestExport_DefaultOutputPath(t *testing.T) {
	e := gitlab.New()
	if e.DefaultOutputPath() != ".gitlab-ci.yml" {
		t.Errorf("expected '.gitlab-ci.yml', got %q", e.DefaultOutputPath())
	}
}

func TestExport_Name(t *testing.T) {
	e := gitlab.New()
	if e.Name() != "gitlab" {
		t.Errorf("expected 'gitlab', got %q", e.Name())
	}
}

// --- needs: (DAG) ---

func TestExport_Needs_RenderedAsGitLabNeeds(t *testing.T) {
	e := gitlab.New()
	p := pipeline(map[string]*schema.Job{
		"build": job("ubuntu-latest", runStep("", "go build")),
		"test":  {RunsOn: "ubuntu-latest", Needs: []string{"build"}, Steps: []*schema.Step{runStep("", "go test ./...")}},
	})
	out, err := e.Export(p)
	if err != nil {
		t.Fatalf("Export() error: %v", err)
	}
	if !strings.Contains(string(out), "needs:") {
		t.Errorf("expected 'needs:' in output, got:\n%s", string(out))
	}
}

// --- env / variables ---

func TestExport_JobEnv_RenderedAsVariables(t *testing.T) {
	e := gitlab.New()
	j := job("ubuntu-latest", runStep("", "echo $FOO"))
	j.Env = map[string]string{"FOO": "bar"}
	out, err := e.Export(pipeline(map[string]*schema.Job{"build": j}))
	if err != nil {
		t.Fatalf("Export() error: %v", err)
	}
	if !strings.Contains(string(out), "variables:") {
		t.Errorf("expected 'variables:' in output, got:\n%s", string(out))
	}
	if !strings.Contains(string(out), "FOO: bar") {
		t.Errorf("expected 'FOO: bar' in output, got:\n%s", string(out))
	}
}

// --- timeout ---

func TestExport_Timeout_RenderedCorrectly(t *testing.T) {
	e := gitlab.New()
	j := job("ubuntu-latest", runStep("", "sleep 60"))
	j.TimeoutMinutes = 30
	out, err := e.Export(pipeline(map[string]*schema.Job{"build": j}))
	if err != nil {
		t.Fatalf("Export() error: %v", err)
	}
	if !strings.Contains(string(out), "30 minutes") {
		t.Errorf("expected '30 minutes' in output, got:\n%s", string(out))
	}
}

// --- uses: shims ---

func TestExport_CheckoutShim_GoesInBeforeScript(t *testing.T) {
	e := gitlab.New()
	j := job("ubuntu-latest",
		usesStep("actions/checkout@v4"),
		runStep("Build", "go build"),
	)
	out, err := e.Export(pipeline(map[string]*schema.Job{"build": j}))
	if err != nil {
		t.Fatalf("Export() error: %v", err)
	}
	if !strings.Contains(string(out), "before_script:") {
		t.Errorf("expected 'before_script:' for checkout action, got:\n%s", string(out))
	}
}

func TestExport_UnknownAction_EmitsComment(t *testing.T) {
	e := gitlab.New()
	j := job("ubuntu-latest", usesStep("some-org/some-action@v1"))
	out, err := e.Export(pipeline(map[string]*schema.Job{"build": j}))
	if err != nil {
		t.Fatalf("Export() error: %v", err)
	}
	if !strings.Contains(string(out), "no direct GitLab equivalent") {
		t.Errorf("expected 'no direct GitLab equivalent' comment, got:\n%s", string(out))
	}
}

// --- matrix ---

func TestExport_Matrix_RenderedAsParallel(t *testing.T) {
	e := gitlab.New()
	j := &schema.Job{
		RunsOn: "ubuntu-latest",
		Steps:  []*schema.Step{runStep("", "go test")},
		Strategy: &schema.Strategy{
			Matrix: map[string]interface{}{
				"go-version": []interface{}{"1.20", "1.21"},
			},
		},
	}
	out, err := e.Export(pipeline(map[string]*schema.Job{"test": j}))
	if err != nil {
		t.Fatalf("Export() error: %v", err)
	}
	if !strings.Contains(string(out), "parallel:") {
		t.Errorf("expected 'parallel:' in output, got:\n%s", string(out))
	}
	if !strings.Contains(string(out), "matrix:") {
		t.Errorf("expected 'matrix:' in output, got:\n%s", string(out))
	}
}

// --- workflow name ---

func TestExport_PipelineName_RenderedAsWorkflow(t *testing.T) {
	e := gitlab.New()
	out, err := e.Export(pipeline(map[string]*schema.Job{
		"build": job("ubuntu-latest", runStep("", "echo hi")),
	}))
	if err != nil {
		t.Fatalf("Export() error: %v", err)
	}
	if !strings.Contains(string(out), "workflow:") {
		t.Errorf("expected 'workflow:' in output, got:\n%s", string(out))
	}
}

// --- self-hosted tags ---

func TestExport_SelfHosted_UsesTags(t *testing.T) {
	e := gitlab.New()
	j := &schema.Job{
		RunsOn: []interface{}{"self-hosted", "linux"},
		Steps:  []*schema.Step{runStep("", "echo hi")},
	}
	out, err := e.Export(pipeline(map[string]*schema.Job{"build": j}))
	if err != nil {
		t.Fatalf("Export() error: %v", err)
	}
	if !strings.Contains(string(out), "tags:") {
		t.Errorf("expected 'tags:' for self-hosted runner, got:\n%s", string(out))
	}
}

// --- empty pipeline ---

func TestExport_EmptySteps_HasFallbackScript(t *testing.T) {
	e := gitlab.New()
	j := &schema.Job{RunsOn: "ubuntu-latest", Steps: []*schema.Step{usesStep("actions/checkout@v4")}}
	out, err := e.Export(pipeline(map[string]*schema.Job{"build": j}))
	if err != nil {
		t.Fatalf("Export() error: %v", err)
	}
	_ = string(out) // just ensure no panic / crash
}
